Reducers
AJ193/Book-Store-React pull request #2
Opened 2023-06-12 08:46 UTC by AJ193

### In this branch I did the following:

- Installed react-redux
- Created store.js
- Created books.js
- Created categories.js

2023-06-12 09:42 UTC, ishimwezachee requested changes
Hi @AJ193 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://media3.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif)

## Highlights
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-12 09:42 UTC, ishimwezachee commented on src/redux/books/books.js
> +};
- [ ]  You did an amazing job to implement redux, but I would suggest to improve it a little bit. Reduxjs/toolkit has a very amazing tool `createSlice` method.  Consider using it in your codes because it help to reduce Redux biolerplate, Simplifies Reducer Logic, clear code structure, etc.  Check here for more [info](https://redux-toolkit.js.org/api/createslice)
![image](https://github.com/AJ193/Book-Store-React/assets/43877689/06086b14-abac-4300-900a-f6ccb1e19df5)

2023-06-12 09:42 UTC, ishimwezachee commented on src/redux/categories/categories.js
> +export default categoriesReducer;
- [ ]  You did an amazing job to implement redux, but I would suggest to improve it a little bit. Reduxjs/toolkit has a very amazing tool `createSlice` method.  Consider using it in your codes because it help to reduce Redux biolerplate, Simplifies Reducer Logic, clear code structure, etc.  Check here for more [info](https://redux-toolkit.js.org/api/createslice)
![image](https://github.com/AJ193/Book-Store-React/assets/43877689/60e67c32-d49d-4a5d-a10c-c56ad4094c23)

2023-06-13 08:25 UTC, ShadyShawkat approved these changes
## Hi @AJ193, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 
- Your readme looks professional ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 08:25 UTC, ShadyShawkat commented on src/redux/rootRiducers.js
> +export default MyrootReducer;
- [x] Kindly remove one of the stores, you don't need two stores each with its slices, you'll only need one.

2023-06-13 08:28 UTC, AJ193 commented on src/redux/rootRiducers.js
> +export default MyrootReducer;
@ShadyShawkat ok Thanks for approving

2023-06-13 08:28 UTC, merged